---
title: Taller de revisión de software por pares en rOpenSci
sbtitle: Dia 2
author: Mauro Lepore
date: last-modified
format: revealjs
---

# Objetivos

Día 1

1. Entender las etapas y qualidades mas importantes del proceso de revision por pares en rOpenSci
2. Ejercitar el proceso para proponer software para revision
3. Instalar pkgcheck

Día 2

4. Ejercitar el proceso para enviar software para revision


#  Día 2: 4. Ejercitar el proceso para enviar software para revision:


- Profundizar en alcance
- Usar pkgcheck para detectar y corregir problemas
- Revisar y responder a una revision de forma constructiva y amable


## Repaso

El paquete [karel](https://github.com/ropensci/software-review/issues/620) enseña a programar. Su objetivo esta fuera del alcance de rOpenSci. Fue propuesto para revisión en 2023, durente el programa de campeone/as.

Es correcto que haya ser revisado en rOpenSci?

- Si porque encaja en alcance
- No porque no encaja en el alcance
- Si porque aunque no encaja an el alcance es una excepción.

## Como autor/a enviar software para revisión

- Identificar la categoría de un paquete
- Generar e interpretar el resultado de pkgcheck
- Corregir problemas detectados por pkgcheck

## Como revisor/a revisar una parte del paquete de forma constructiva y amable

- Escribir un encabezado
- Completar una parte del review-template
- Escribir un comentario ofreciendo una sugerencia de cambio

## Como author/a responder a la revisión de forma constructiva y amable 

- Modificar el paquete
- Escribir una respuesta explicando el cambio.

## Explorar detalles del proceso y generar preguntas

- Explorar issues reales etiquetados con [6/approved](https://github.com/ropensci/software-review/issues?q=state%3Aclosed%20label%3A%226%2Fapproved%22).

## Repaso

Escribi reflexiones que cuenten la historia de lo que vimos

- Que? ej. Un paso que no practicamos es ...
- Quien? ej. Tipicamente quien cambia las etiquetas del issue es ...
- Donde? ej. El/la editor/a busca revisore/as en ... 
- Como? ej. El/la editor/a contacta revisore/as mediante ... 
- Cuando? ej. El/la autor/a respnde a la revision cuando ... 
- Por que? ej. El proceso es publico y transparente porque ...

## Cierre

FIXME

- with impressions compared to academia
- feedback
- invite to subscrive to become a reviewer via the form and ask to spread the word
