---
title: Taller de revisi칩n de software por pares de rOpenSci
date: last-modified
author: Mauro Lepore
format:
  revealjs:
    slide-number: true
    scrollable: true
    mermaid-format: svg
---

# Introducci칩n al taller

Hola, soy [Mauro](https://ropensci.org/author/mauro-lepore/) 游녦. Este taller para [vos](https://ropensci.org/es/champions/) 游끤游쀯릖

<br>
<br>
<br>
<br>
<br>
<br>
<br>

<sub>
Licencia: [Atribuci칩n/Reconocimiento-NoComercial 4.0 Internacional](https://creativecommons.org/licenses/by-nc/4.0/deed.es)
</sub>

## Objetivos principales

D칤a 1

- Familiarizarse con las etapas y cualidades del proceso
- Practicar proponer software para revisi칩n

D칤a 2

- Practicar enviar software para revisi칩n

## Plan para hoy

- `00:00` Introducci칩n al taller
- `00:05` Introducci칩n al proceso de punta a punta
  - `00:10` Comparacion con la academia
  - `00:20` Proponer y enviar software para revisi칩n
  - `00:30` {pkgcheck}
  - `00:40` Codigo de conducta y comunicacion
- `00:55` Pausa
- `01:05` Proponer software para revisi칩n
  - `01:10` Abrir issue
  - `01:25` Comunicacion amable y constructiva
- `01:40` Preguntas y respuestas

# Introducci칩n al proceso de punta a punta

La forma en la que trabajamos con [software](https://devguide.ropensci.org/es/index.es.html) y [personas](https://ropensci.org/es/c%C3%B3digo-de-conducta/)

## Comparaci칩n con la academia

En la academia y en rOpenSci ...

- 쮺u치l es la motivaci칩n de un/a autor/a o revisor/a?
- 쯈u칠 otros roles participan?
- 쯈u칠 medio se usa para la comunicaci칩n?
- 쮺u치ndo se acepta o rechaza un trabajo?
- 쮺칩mo es la comunicaci칩n?

## Proponer software para revisi칩n

```{mermaid}
flowchart LR
    B((1-Abrir issue))
    B --> C{2-쮻entro del alcance?}
    C -->|No| E{3-쮼xcepci칩n?}
    C -->|Si| D[4-Enviar]
    E -->|Si| D
    E -->|No| G((5-Cerrar issue))
```

:::aside
[Paquetes de rOpenSci: Desarrollo, mantenimiento y revisi칩n por pares](https://devdevguide.netlify.app/es/index.es)
:::

## Enviar software para revisi칩n

```{mermaid}
flowchart LR
    B((1-Abrir issue))
    B --> C[2-Revisar]
    C --> D{3-쯃isto?}
    D -->|No| C
    D -->|Si| E((Publicar))
```

:::aside
[Paquetes de rOpenSci: Desarrollo, mantenimiento y revisi칩n por pares](https://devdevguide.netlify.app/es/index.es)
:::

## {pkgcheck}: Uso en un "issue"

```r
@ropensci-review-bot check package
```

<br>

[Ejemplo](https://github.com/ropensci/software-review/issues/593#issuecomment-1608404055)

:::aside
[Comandos del bot](https://devguide.ropensci.org/es/bot_cheatsheet.es.html)
:::

## {pkgcheck}: Uso local

Instalaci칩n

```r
  options (repos = c (
    ropenscireviewtools = "https://ropensci-review-tools.r-universe.dev",
    CRAN = "https://cloud.r-project.org"
  ))
  install.packages("pkgcheck")
```

<br>

Ejemplo

```r
  paquete <- "/camino/al/paquete"
  resultados <- pkgcheck::pkgcheck(paquete)
  resultados
  
  summary(resultados)
```

:::aside
[Documentacion de {pkgcheck}](https://docs.ropensci.org/pkgcheck/)
:::

## C칩digo de Conducta

- La comunidad es nuestro mejor activo
- Nuestra diversidad es nuestra fortaleza
- No toleramos ning칰n tipo de acoso

:::aside
[C칩digo de Conducta](https://ropensci.org/es/c%C3%B3digo-de-conducta/)
:::

## Comunicaci칩n amable y constructiva

<br>

Ofrecer

- Seguridad
- Sugerencia/Sentencia
- Seguimiento

::: aside
[C칩mo ganar amigos e influir sobre las personas](https://www.amazon.com/-/es/influir-personas-Friends-Influence-Spanish/dp/164473009X)  
[Conversaciones Cruciales: herramientas para comunicar mejor cuando m치s se necesita](https://www.amazon.com/Conversaciones-Cruciales-Edici%C3%B3n-revisada-conocimiento-ebook/dp/B01EX1TZQG/ref=sr_1_1?adgrpid=167955646707&dib=eyJ2IjoiMSJ9.Ws1WzIBF0cC2Dm2-H47hguDVuXRPmMy9rZLGRYA4t3ER8EP9QL1L1dPW8a2l0c2aI65gElZhBVvYTfIcqtuaBVQcnOAmIBffgVzFQKm44rUISeaXgEIVBBw4-muztHHDiwE9jwRJSFYtSDFMAq4h9Rvb-GvpCxfZNzbfBApAjBAXNIQ63XVjTnFrOly1C-YCBSC8uEVyOljvl5CfMMfShGRKX-fYLjSLXyU0CJW-xuk.LRH-a9xfbt1VH_6O1wTX-6nxoUp_g1gSKmBPfElISuA&dib_tag=se&hvadid=730129623296&hvdev=c&hvlocphy=9070297&hvnetw=g&hvqmt=e&hvrand=357311298508997420&hvtargid=kwd-319512755646&hydadcr=23800_13790585&keywords=conversaciones+cruciales&mcid=bd94c27aa7253eda9e137472f79bfcd2&qid=1763123775&sr=8-1)
:::

## Comunicaci칩n amable y constructiva

Explica c칩mo y por qu칠 el paquete se incluye en estas categor칤as.

> [`@szimmer` (autora)](https://github.com/ropensci/software-review/issues/726#issue-3465625692): Esto no encajaba exactamente en ninguna categor칤a predefinida, as칤 que agregu칠 la m칤a propia. Implementa algoritmos de muestreo estad칤stico

[`@mpadge` (editor)](https://github.com/ropensci/software-review/issues/726#issuecomment-3350567704)

<details><summary>Respuesta 1 (editado)</summary>

> @szimmer, las categor칤as de estad칤stica est치n literalmente codificadas en forma de nuestra serie de est치ndares espec칤ficos por categor칤a. Esperamos y planeamos expandir las categor칤as lentamente, pero no podemos hacerlo en respuesta a env칤os individuales.

</details>

<details><summary>Respuesta 2 (editado)</summary>

> Gracias por consultar aqu칤 @szimmer. Este parece un paquete muy interesante, pero desafortunadamente las categor칤as de estad칤stica est치n literalmente codificadas en forma de nuestra serie de est치ndares espec칤ficos por categor칤a. Esperamos y planeamos expandir las categor칤as lentamente, pero no podemos hacerlo en respuesta a env칤os individuales.

</details>

<details><summary>Respuesta 3 (editado)</summary>

> Gracias por consultar aqu칤 @szimmer. Este parece un paquete muy interesante, pero desafortunadamente las categor칤as de estad칤stica est치n literalmente codificadas en forma de nuestra serie de est치ndares espec칤ficos por categor칤a. Esperamos y planeamos expandir las categor칤as lentamente, pero no podemos hacerlo en respuesta a env칤os individuales.

> Dicho esto, he revisado un poco tu paquete y veo una posibilidad en la categor칤a de Distribuciones de Probabilidad. ... La adaptaci칩n para cumplir con nuestros est치ndares de Distribuciones de Probabilidad requerir칤a modificar el comportamiento de muestreo subyacente, para permitir el muestreo de formas distribucionales espec칤ficas.

> ...

> Por favor d칠jame saber qu칠 piensas.

(Diez dias mas tarde)

> @szimmer Do you have any thoughts in response to my suggestions above?

</details>

## Comunicaci칩n amable y constructiva

<br>

Mas ejemplos

{eph}

<details><summary>[Revisi칩n de `@guadag12`](https://github.com/ropensci/software-review/issues/593#issuecomment-1709968472)</summary>

Seguridad

> Antes que nada, felicitaciones por el paquete. ... En t칠rminos generales funciona muy bien, corre r치pido, es simple de usar y tiene mucha informaci칩n. 

Sugerencia

> Ahora s칤, procedo a la review siguiendo las recomendaciones de rOpenSci:
> ...
> De todo lo que mencion칠 tal vez le prestar칤a atenci칩n a dos aspectos:
> - Los ejemplos de las funciones que mencionaba arriba. ...
> - Los test unitarios en las funciones que consideren m치s relevantes los agregar칤a. ...

Seguimiento

> Una vez que eso est치, creo que estamos para avanzar 游땕. Gran trabajo,

</details>

<details><summary>[Respuesta de `@caropradier`](https://github.com/ropensci/software-review/issues/593#issuecomment-1714421144)</summary>

Seguridad

> @lidefi87 gracias de nuevo por tus esfuerzos!

Sugerencia

> Respecto al nombre de las funciones, intentar칤a no hacer modificaciones mayores para no perturbar el flujo de trabajo de nuestros usuarios actuales (aproximadamente 30 mil personas usan el paquete y quisiera evitar generarles inconvenientes si no se trata de algo fundamental para el funcionamiento del paquete). No obstante, estoy de acuerdo con que se trata de una buena pr치ctica, y lo tendr칠 presente al incorporar nuevas funciones.

</details>

{agroclimatico}

<details><summary>[Revisi칩n de `@VeruGHub`](https://github.com/ropensci/software-review/issues/599#issuecomment-1936698026)</summary>

Seguridad

> En primer lugar, quiero agradecer la oportunidad de revisar este paquete y espero que los comentarios sirvan para mejorar en los puntos que los autores consideren oportunos. Creo que los autores han hecho un gran trabajo compilando las funciones relacionadas con la gesti칩n de datos clim치ticos que son 칰tiles para el INTA.

Sugerencia

> Creo que algunos aspectos formales de la documentaci칩n pueden ser mejorados. Para empezar, la funcionalidad del paquete no est치 completamente definida en la documentaci칩n (Readme) ... Mejorar estas descripciones e incluir programaci칩n defensiva relativa a los argumentos (en general faltante) ayudar칤a mucho a los usuarios.

</details>

<details><summary>[Respuesta de `@paocorrales`](https://github.com/ropensci/software-review/issues/599#issuecomment-2143389578)</summary>

Seguridad

> En primer lugar, muchas gracias @pmnatural y @VeruGHub por la revisi칩n y los comentarios, y a @Pakillo por ordenarlos y organizar todo.

Sugerencia

> Incorpor칠 los comentarios y sugerencias al paquete. ...

Seguimiento

> Espero no haberme olvidado de nada, aguardo sus comentarios!

</details>


# Pausa
# Proponer software para revisi칩n

## Abrir issue

Abr칤 un issue para proponer software en el [repositorio de pr치ctica](https://github.com/maurolepore/software-review/issues). Pod칠s usar tu paquete o cualquiera de estos: [eph](https://github.com/ropensci/software-review/issues/593), [karel](https://github.com/ropensci/software-review/issues/620), [agroclimatico](https://github.com/ropensci/software-review/issues/599).

## Comunicar amablemente

Como editor/a, escribir un comentario constructivo y amable notificando que el paquete est치 fuera del alcance de rOpenSci.

A modo de ejemplo pod칠s usar [karel](https://github.com/ropensci/software-review/issues/620), que fue revisado como excepci칩n por el programa de campeones/as pero que normalmente est치 fuera del alcance de las categor칤as de rOpenSci.

# Preguntas y respuestas

(10') Explorar los detalles del proceso para proponer software para revisi칩n y generar preguntas, sobre lo que vimos y lo que no vimos hoy:

- Explorar la [plantilla real de propuesta de software para revisi칩n](https://github.com/ropensci/software-review/issues)
- Explorar issues reales etiquetados con [0/presubmission](https://github.com/ropensci/software-review/issues?q=is%3Aissue%20label%3A0%2Fpresubmission)

(10') Respuestas.


# Ejercicios

## {{< fa edit >}} El proceso para proponer software para revisi칩n

```{mermaid}
flowchart LR
    B((1-___________))
    B --> C{2-쮻entro del alcance?}
    C -->|No| E{3-___________}
    C -->|Si| D[4-_______]
    E -->|Si| D
    E -->|No| G((5-Cerrar issue))
```

a. 쮼xcepci칩n?
b. Enviar
c. Abrir issue

## {{< fa edit >}} El proceso para enviar software para revisi칩n

El proceso para enviar software para revisi칩n

```{mermaid}
flowchart LR
    B((1-Abrir issue))
    B --> C[2-_______]
    C --> D{3-쯃isto?}
    D -->|No| C
    D -->|Si| E((4-________))
```

a. Publicar
b. Revisar

## {{< fa edit >}} Comunicaci칩n: Estructura

### La estructura del feedback constructivo y amable

- Como revisor/a, escrib칤 una introducci칩n m칤nima pero constructiva y amable como encabezado para una revisi칩n imaginaria.

- Como autor/a, escrib칤 una introducci칩n m칤nima pero constructiva y amable como encabezado para tus respuestas imaginarias a las sugerencias de un/a revisor/a.

## {{< fa edit >}} Reflexiones

Escribir reflexiones que cuenten la historia de lo que vimos

- 쯈u칠? ej. Las actividades principales del proceso son ...
- 쯈ui칠n? ej. Los roles que participan en la presubmisi칩n son ...
- 쮺칩mo? ej. El feedback debe ser ...
- 쮻칩nde? ej. Todo el proceso ocurre en ....
- 쯇or qu칠? e.g. La revisi칩n por pares ayuda a ...
- 쮺u치ndo? ej. La evaluaci칩n de alcance debe hacerse antes de ...


## Recursos

- FIXME Repositorio de pr치ctica: <https://github.com/maurolepore/software-review>
- FIXME [Documento colaborativo](https://bit.ly/taller-de-revision-de-software-por-pares-de-ropensci)
- [C칩digo de Conducta](https://ropensci.org/es/c%C3%B3digo-de-conducta/)
- Libro [Paquetes de rOpenSci: Desarrollo, mantenimiento y revisi칩n por pares](https://devdevguide.netlify.app/es/index.es)
- [pkgcheck](https://docs.ropensci.org/pkgcheck/)
- Paquetes de campeones/as en espa침ol:
  - [eph](https://github.com/ropensci/software-review/issues/593)
  - [agroclimatico](https://github.com/ropensci/software-review/issues/599)
  - [karel](https://github.com/ropensci/software-review/issues/620)
- Blogs sobre el proceso de revisi칩n:
  - [Revisi칩n del software, perspectivas de un acad칠mico](https://ropensci.org/es/blog/2025/03/25/r-package-review/) (Alex Koiter, autor)
  - [Experiencias revisando paquetes de rOpenSci por primera vez](https://ropensci.org/es/blog/2017/09/08/first-review-experiences/) (Verena Haunschmid, revisora)
  - [As칤 que (no) crees que puedas revisar un paquete](https://ropensci.org/es/blog/2017/08/22/first-package-review/) (Mara Averick revisora)
- Blog sobre comunicaci칩n en open source: [Setting expectations for open source participation](https://snarky.ca/setting-expectations-for-open-source-participation/)
