---
title: Taller de revisión de software por pares en rOpenSci
date: last-modified
---

# Esquema

## Día 1: Proponer software para revisión

Objetivos:

- Como autor/a proponer un paquete para revisión
- Familiarizarse con el alcance y excepciones de rOpenSci
- Entender por qué y cómo dar feedback constructivo y amable
- Instalar pkgcheck

## Día 2: Enviar software para revisión

Objetivos:

- Profundizar en alcance
- Usar pkgcheck para detectar y corregir problemas
- Como revisor/a revisar parte de un paquete de forma constructiva y amable
- Como autor/a responder a una revisión de forma constructiva y amable 

#  Día 1: Proponer software para revisión

## Como es el proceso de revision por pares en academia?

Describir el proceso de revision por pares en academia. Enfocate en cualquier aspecto especifico del proceso. 

Por ejemplo:

- (Que?) Las etapas basicas del proceso son ...
- (Quien?) Los roles mas comunes son ...
- (Como?) La cumunicacion es ...
- (Donde) La plataforma donde ocurre es ...
- (Por que) La motivacion de un/a autor/a o revisor/a es ...
- (Cuando) El trabajo se rechaza o publica cuando ...

## El proceso de revisión en rOpenSci

- Etiquetar el [diagrama de flujo de trabajo](https://lucid.app/lucidchart/8be1a782-2426-4996-b0a7-405d5b2ebf2a/edit?invitationId=inv_3c869d3f-ec90-4989-9907-2a8d60350425&page=0_0#)

```{mermaid}
flowchart LR
    B((1-___________))
    B --> C{2-¿Dentro del alcance?}
    C -->|No| E{3-___________}
    C -->|Si| D[4-_______]
    E -->|Si| D
    E -->|No| G((5-Cerrar issue))
```

a. ¿Excepcion?
b. Revisar
c. Abrir issue

<details><summary>Solución</summary>

```{mermaid}
flowchart LR
    B((1-Abrir issue))
    B --> C{2-¿Dentro del alcance?}
    C -->|No| E{3-¿Excepcion?}
    C -->|Si| D[4-Revisar]
    E -->|Si| D
    E -->|No| G((5-Cerrar issue))
```

</details>

## Ejercitar el proceso simplificado para proponer software para revisión

- Escribir un comendario constructivo y amable notificando que el paquete esta fuera del alcance.

## Explorar detalles del proceso y generar preguntas

- Explorar la [plantilla real de propuesta de software para revisión](https://github.com/ropensci/software-review/issues)
- Explorar issues reales etiquetados con [0/presubmission](https://github.com/ropensci/software-review/issues?q=is%3Aissue%20label%3A0%2Fpresubmission)

## Instalar [pkgcheck](https://docs.ropensci.org/pkgcheck/)

```r
install.packages ("pkgcheck")
```

## Repaso

Escribir reflexiones que cuenten la historia de lo que vimos

- Que? ej. Las actividades principlaes del proceso son ...
- Quien? ej. Los roles que participan en la pre-submision son ...
- Como? ej. El feedback debe ser ...
- Donde? ej. Todo el proceso ocurre en ....
- Por que? e.g. La revision por pares ayuda a ...
- Cuando? ej. La evaluacion de alcance debe hacerse antes de ... 

#  Día 2: Enviar software para revisión

## Repaso

El paquete [karel](https://github.com/ropensci/software-review/issues/620) enseña a programar. Su objetivo esta fuera del alcance de rOpenSci. Fue propuesto para revisión en 2023, durente el programa de campeone/as.

Es correcto que haya ser revisado en rOpenSci?

- Si porque encaja en alcance
- No porque no encaja en el alcance
- Si porque aunque no encaja an el alcance es una excepción.

## Como autor/a enviar software para revisión

- Identificar la categoría de un paquete
- Generar e interpretar el resultado de pkgcheck
- Corregir problemas detectados por pkgcheck

## Como revisor/a revisar una parte del paquete de forma constructiva y amable

- Escribir un encabezado
- Completar una parte del review-template
- Escribir un comentario ofreciendo una sugerencia de cambio

## Como author/a responder a la revisión de forma constructiva y amable 

- Modificar el paquete
- Escribir una respuesta explicando el cambio.

## Explorar detalles del proceso y generar preguntas

- Explorar issues reales etiquetados con [6/approved](https://github.com/ropensci/software-review/issues?q=state%3Aclosed%20label%3A%226%2Fapproved%22).

## Repaso

Escribi reflexiones que cuenten la historia de lo que vimos

- Que? ej. Un paso que no practicamos es ...
- Quien? ej. Tipicamente quien cambia las etiquetas del issue es ...
- Donde? ej. El/la editor/a busca revisore/as en ... 
- Como? ej. El/la editor/a contacta revisore/as mediante ... 
- Cuando? ej. El/la autor/a respnde a la revision cuando ... 
- Por que? ej. El proceso es publico y transparente porque ...

## Cierre

FIXME

- with impressions compared to academia
- feedback
- invite to subscrive to become a reviewer via the form and ask to spread the word

# Links

- Repositorio de apoyo: [maurolepore/sofware-review](https://github.com/maurolepore/software-review)
  - TODO move to https://github.com/ropensci-training 
  - Plantillas de issues imitando a ropensci/software-review
  - Slides
- TODO documento colaborativo
- [devguide](https://devdevguide.netlify.app/es/index.es) 
- [pkgcheck](https://docs.ropensci.org/pkgcheck/)
- Paquete de practica: TODO
- Ejemplos de paquetes en Español: TODO
- Blogs sobre el proceso de revision:
  - [Revisión del software, perspectivas de un académico](https://ropensci.org/es/blog/2025/03/25/r-package-review/) (Alex Koiter, autor)
  - [Experiencias revisando paquetes de rOpenSci por primera vez](https://ropensci.org/es/blog/2017/09/08/first-review-experiences/) (Verena Haunschmid, revisora)
  - [Así que (no) crees que puedas revisar un paquete](https://ropensci.org/es/blog/2017/08/22/first-package-review/) (Mara Averick revisora)
